### ISSUE TITLE
About the pre-training model

### ISSUE THREAD

**Issue by FXMEIa** [lyres/SRHEN#1]
Hello, can you share the pre training model

**Comment by lyres** [comment]
I have uploaded the trained model.
Link: https://pan.baidu.com/s/1u-9Bu72OY_wC7CoocorZXQ?pwd=94rq Extraction Code: 94rq

**Comment by FXMEIa** [comment]
I encountered some problems when synthesizing data. When using the known offset estimation H, the error is as follows:

Traceback (most recent call last):
  File "F:/Homography/new_H/SRHEN-main/test.py", line 54, in <module>
    for data in dataset:
  File "C:\Users\XM\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\XM\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\XM\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\XM\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\Homography\new_H\SRHEN-main\Dataset.py", line 50, in __getitem__
    img2 = cv2.warpPerspective(img1, tform, (self.imageW, self.imageH))
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\imgproc\src\imgwarp.cpp:3144: error: (-215:Assertion failed) _src.total() > 0 in function 'cv::warpPerspective'

**Comment by lyres** [comment]
Maybe the image is not read successfully. See the 41-42 lines in MSCOCO.py. You should rename your images as 000000.jpg, 000001.jpg, etc. or change the code according to your image names.
41        # Read and warp image
42        img1 = cv2.imread(self.dir_img + '%06d.jpg' % idx)

**Comment by FXMEIa** [comment]
这个网络结构是最终的多尺度的版本嘛？

**Comment by lyres** [comment]
这个不是最初的（原文的）多尺度版本。与原文版本的不同之处已经在 readme.md 文件中列出来了。这个版本比原文的版本更加精简，单次预测精度也更高。

原文版本的实现使用VGG网络作为骨干（因为之前很多方法都是用VGG网络作为骨干，使用这个网络是为了便于比较），但后来我们发现使用VGG网络的效果并不是很理想，所以才想着通过多尺度迭代的机制来提高预测精度。

这个版本的实现使用ResNet网络作为骨干，即使没有使用多尺度的机制，也达到了很不错的效果，所以我们就把多尺度以及原文中的金字塔监督机制都取消了。

当然，如果您想实现更高的预测精度，还是可以使用多尺度预测，或者单纯使用迭代预测（就是同一个模型预测多次，每次输入矫正之后的图像对）。多尺度或迭代预测都会导致预测时间增加，所以根据您的应用场景来选择吧。

不管您是用于学术还是工程，都建议您使用我们当前的版本。

**Comment by FXMEIa** [comment]
是加载模型直接运行test.py文件嘛？我得到的RMSE值有些高，不知道是不是我哪里出错了。

**Comment by lyres** [comment]
要先把图像缩放到320*320。可以用preprocess_images_offline.py这个程序进行图像缩放，改改程序里的路径和参数就行了，很简单的。

**Comment by FXMEIa** [comment]
是的，我将图像resize成320*320大小，然后改改路径直接测试的，我测了5K张图像，MACE=35.17
[Testing SRHEN on MSCOCO]
C:\Users\XM\Anaconda3\envs\pytorch1.7\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
	Testing on model: 40, MACE=35.17

**Comment by lyres** [comment]
我把代码下下来，自己也测了下，MACE=1.25。代码和训练好的模型都没问题。您那边也是测的MSCOCO数据集吗（只要是常见的图像应该都没问题）？如果是的话不应该会出现这样的问题。您再检查下，是不是改动哪了？版本问题的概率应该很低，实在不行也可以试试建一个跟我一样的虚拟环境来跑。
(pytorch001) H:\SRHEN-main>python test.py
[Testing SRHEN on MSCOCO]
        Testing on model: 40, MACE=1.25

**Comment by lyres** [comment]
代码能跑通，说明模型被成功加载了。您那边测试出现这么大一个MACE值，以我的经验，最大的可能是您测试的图像是原始的图像而不是320*320的图像，您检查下路径是不是弄错了？

**Comment by FXMEIa** [comment]
您好，我还想问一下，就是在原来的多尺度版本中，计算最终H的时候，为什么要使用多个尺度的H相乘的方式呀？










在 2022-10-04 15:20:30，"lyres" ***@***.***> 写道：

这个不是最初的（原文的）多尺度版本。与原文版本的不同之处已经在 readme.md 文件中列出来了。这个版本比原文的版本更加精简，单次预测精度也更高。

原文版本的实现使用VGG网络作为骨干（因为之前很多方法都是用VGG网络作为骨干，使用这个网络是为了便于比较），但后来我们发现使用VGG网络的效果并不是很理想，所以才想着通过多尺度迭代的机制来提高预测精度。

这个版本的实现使用ResNet网络作为骨干，即使没有使用多尺度的机制，也达到了很不错的效果，所以就把多尺度以及原文中的金字塔监督机制都取消了。

当然，如果你想实现更高的预测精度，还是可以使用多尺度预测，或者单纯使用迭代预测（就是同一个模型预测多次，每次输入矫正之后的图像对）。多尺度或迭代预测都会导致预测时间增加，所以根据您的应用场景来选择吧。

不管您是用于学术还是工程，都建议您使用我们当前的版本。

**Comment by lyres** [comment]
在方法部分，为了方便描述，H用的是3X3矩阵形式，连续变换就是通过矩阵乘法来实现的。这个地方就是简单的矩阵和矩阵/向量的乘法，应该很好理解吧。比如，X2 = H1 * X1，X3 = H2 * X2 = H2 * (H1 * X1) = (H2 * H1) * X1，这里的X1~3为齐次坐标（1X3的坐标向量），H2和H1分别是第二次和第一次变换（3X3的变换矩阵）。

在实现中，为了便于优化，一般都是用4-point的形式来表达H，也就是用一个1X8的向量来表达H。
这两种表达H的方式是可以互相转换的，如果要用这个1X8的向量来对图像进行变换，那就得先讲将这个1X8的向量转换成3X3的矩阵形式，然后再用矩阵形式的H来对图像进行变换。连续变换是不能通过向量形式的H来直接相乘得到的。不知道这么解释您能否理解。
